# code the pipeline 
name: CI/CD Pipeline for Bank Marketing Data

# Trigger the workflow on push or pull request events for the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ml_pipeline:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Step 2: Set up Python 3.8 environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Step 3: Install required dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn pytest

      # Step 4: Run Preprocessing Script (preprocessing.py)
      - name: Run Preprocessing
        run: |
          python preprocessing.py

      # Step 5: Run Model Training Script (train_model.py)
      - name: Train Model
        run: |
          python train_model.py

      # Step 6: Run Test Cases using pytest
      - name: Run Tests
        run: |
          pytest tests/  # Adjust this path if necessary to your test folder

